### PR TITLE
Mp3 fix

### PR DESCRIPTION
**Pull request by Sumit112192**
Added a default dowload location so no need to select location all the time.
Added mp3 option: ytdownloader first downloads the file in mp4a format and then converts it into mp3 using pydub and finally deletes the mp4a file.

### CODE REVIEW

**Comment by sanskar10100** [comment]
image

Stacktrace above. The download button does no action. Please resolve this issue.

**Comment by utgupta27** [comment]
Screenshot 2020-12-27 185602
**Unable to download the Required MP3 format and shows an error warning after successfull Download **

**Comment by Sumit112192** [comment]
Let me see

**Comment by Sumit112192** [comment]
> Screenshot 2020-12-27 185602
> **Unable to download the Required MP3 format and shows an error warning after successfull Download **

Did you **pip install pydub** ??

**Comment by utgupta27** [comment]
yup

**Comment by Sumit112192** [comment]
> yup

Can you share the video link....

**Comment by oo7coolutsav** [comment]
https://www.youtube.com/watch?v=A0314QOklz8

**Comment by Sumit112192** [comment]
Its Working!!!
I guess you have to make a directory named Downloads manually in ytdownloader/src/Downloads
DeepinScreenshot_20201227191638

**Comment by Sumit112192** [comment]
> https://www.youtube.com/watch?v=A0314QOklz8

Reply whether the issue is resolved or  not and maybe we can add if such directory doesn't exist we can automatically create it using python

**Comment by Sumit112192** [comment]
> image
> 
> Stacktrace above. The download button does no action. Please resolve this issue

> image
> 
> Stacktrace above. The download button does no action. Please resolve this issue.

I didn't even touched things related with filesize. This errors were coming early also when I started working on it but even after that everything was working fine.

**Comment by sanskar10100** [comment]
**Created the Download folder in the src dir.**
image

**Used this link:** 
image

**Selected the mp3 option. Download began:**
image

**Download failed upon reaching 100:**
image

**This is the stacktrace after download failure:**
image

**But, when I checked the Downloads folder inside the src, I found an mp4 file, which contains no video, only audio.**
image

image

**Comment by Sumit112192** [comment]
> **Created the Download folder in the src dir.**
> image
> 
> **Used this link:**
> image
> 
> **Selected the mp3 option. Download began:**
> image
> 
> **Download failed upon reaching 100:**
> image
> 
> **This is the stacktrace after download failure:**
> image
> 
> **But, when I checked the Downloads folder inside the src, I found an mp4 file, which contains no video, only audio.**
> image
> 
> image

I got why this error is coming..
This is because of filesystems. Wait a minute, I will modify it and share another Pull request.

**Comment by sanskar10100** [comment]
> > **Created the Download folder in the src dir.**
> > image
> > **Used this link:**
> > image
> > **Selected the mp3 option. Download began:**
> > image
> > **Download failed upon reaching 100:**
> > image
> > **This is the stacktrace after download failure:**
> > image
> > **But, when I checked the Downloads folder inside the src, I found an mp4 file, which contains no video, only audio.**
> > image
> > image
> 
> I got why this error is coming..
> This is because of filesystems. Wait a minute, I will modify it and share another Pull request.

That seems like the most probable cause since it clearly works on Deepin.

**Comment by Sumit112192** [comment]
Hey @sanskar10100 thanks for your detailed discussion. I was able to correct my mistake. Now can you verify whether it is now working properly or not?

**Comment by sanskar10100** [comment]
On it

**Comment by Sumit112192** [comment]
Hey @oo7coolutsav If you want to commit this, remove the video that I have also added by mistake in my pull request.

**Comment by sanskar10100** [comment]
Downloading an audio file still results in a failed download prompt:
image

But, upon checking the Downloads folder in the src directory, I again found an MP4 with no video, just audio.
image

This is the file in VLC. Audio available, no video:
image

This is the stacktrace:
image

**Comment by sanskar10100** [comment]
Seems to be an issue with pydub library on windows.

**Comment by Sumit112192** [comment]
https://stackoverflow.com/questions/51219531/pydub-unable-to-locte-ffprobe

**Comment by Sumit112192** [comment]
> Seems to be an issue with pydub library on windows.
Maybe, anyways in which year are you currently?

**Comment by Sumit112192** [comment]
> Seems to be an issue with pydub library on windows.

Maybe, anyway in which study year are you?

**Comment by sanskar10100** [comment]
We both are in the Junior year.

**Comment by utgupta27** [comment]
> Seems to be an issue with pydub library on windows.

pydub works fine  with .wav file 
For saving and opening of non-wav files like- mp3 etc. You will need a dependency  ffmpeg or libav.

**Comment by Sumit112192** [comment]
> > Seems to be an issue with pydub library on windows.
> 
> pydub works fine  with .wav file 
> For saving and opening of non-wav files like- mp3 etc. You will need a dependency  ffmpeg or libav.

Yes I also saw the same issue on stackoverflow.
They said to download ffmeg and things related to setting it's environmental variables.

**Comment by utgupta27** [comment]
> > > Seems to be an issue with pydub library on windows.
> > 
> > 
> > pydub works fine  with .wav file
> > For saving and opening of non-wav files like- mp3 etc. You will need a dependency  ffmpeg or libav.
> 
> Yes I also saw the same issue on stackoverflow.
> They said to download ffmeg and things related to setting it's environmental variables.

https://github.com/jiaaro/pydub#dependencies

Screenshot_20201227_210953

Yes, It is also mentioned in pydub's documentation.

**Comment by Sumit112192** [comment]
Hey @sanskar10100 @oo7coolutsav 
I have a python file which can be used to download entire playlist.
It uses the same pytube module. If you want I can share the link.

**Comment by Sumit112192** [comment]
https://github.com/Sumit112192/YouTube-Playlist--Downloader.git

Here's the link for playlist downloader.

**Comment by utgupta27** [comment]
> https://github.com/Sumit112192/YouTube-Playlist--Downloader.git
> 
> Here's the link for playlist downloader.

Thanks @Sumit112192  , 
That playlist feature is already in my plan, this will surely help me in completing this project.
IMG_20201227_220336

**Comment by Sumit112192** [comment]
> > https://github.com/Sumit112192/YouTube-Playlist--Downloader.git
> > 
> > Here's the link for playlist downloader.
> 
> Thanks @Sumit112192  , 
> That playlist feature is already in my plan, this will surely help me in completing this project.
> IMG_20201227_220336
> 

What's in your plan?
Share with me. Maybe I can help.

**Comment by utgupta27** [comment]
I am just trying some random stuff to get some experience in python and dart/flutter.
By the way, who are you?

**Comment by utgupta27** [comment]
hey @Sumit112192 ,
I created a new branch, issue a pull request in this new branch - https://github.com/oo7coolutsav/ytdownloader/tree/mp3-fix-pydub , because main branch now has 3 conflicts with this request.
I fixed this MP3-issue using moviepy library in my main branch.

**Comment by Sumit112192** [comment]
> hey @Sumit112192 ,
> I created a new branch, issue a pull request in this new branch - https://github.com/oo7coolutsav/ytdownloader/tree/mp3-fix-pydub , because main branch now has 3 conflicts with this request.
> I fixed this MP3-issue using moviepy library in my main branch.
> 

I am currently in first year bs doing physics.
But doing coding as a hobby. Actually I am coding from the last 4 years.

**Comment by utgupta27** [comment]
> > hey @Sumit112192 ,
> > I created a new branch, issue a pull request in this new branch - https://github.com/oo7coolutsav/ytdownloader/tree/mp3-fix-pydub , because main branch now has 3 conflicts with this request.
> > I fixed this MP3-issue using moviepy library in my main branch.
> 
> I am currently in first year bs doing physics.
> But doing coding as a hobby. Actually I am coding from the last 4 years.

Intresting dude ...
From which University you are persuing Physics?

**Comment by Sumit112192** [comment]
> 
> > > hey @Sumit112192 ,
> > > I created a new branch, issue a pull request in this new branch - https://github.com/oo7coolutsav/ytdownloader/tree/mp3-fix-pydub , because main branch now has 3 conflicts with this request.
> > > I fixed this MP3-issue using moviepy library in my main branch.
> > 
> > I am currently in first year bs doing physics.
> > But doing coding as a hobby. Actually I am coding from the last 4 years.
> 
> Intresting dude ...
> From which University you are persuing Physics?

IIT KANPUR

**Comment by Sumit112192** [comment]
> > https://github.com/Sumit112192/YouTube-Playlist--Downloader.git
> > 
> > Here's the link for playlist downloader.
> 
> Thanks @Sumit112192  , 
> That playlist feature is already in my plan, this will surely help me in completing this project.
> IMG_20201227_220336
> 

You should try pyqt5, it has drag and drop functionality for frontend. And it can be converted for android. That would be cool.
I am going to work on this.
I download a lot of songs from YouTube.

**Comment by sanskar10100** [comment]
The layout looks great @Sumit112192. All the best! Hit [me](linkedin.com/in/sanskar10100) or [Utsav](linkedin.com/in/oo7coolutsav) on LinkedIn if you think we can help!

**Comment by utgupta27** [comment]
> > > https://github.com/Sumit112192/YouTube-Playlist--Downloader.git
> > > Here's the link for playlist downloader.
> > 
> > 
> > Thanks @Sumit112192  ,
> > That playlist feature is already in my plan, this will surely help me in completing this project.
> > IMG_20201227_220336
> 
> You should try pyqt5, it has drag and drop functionality for frontend. And it can be converted for android. That would be cool.
> I am going to work on this.
> I download a lot of songs from YouTube.

okay,
From January 2021, I will try PyQt5 toolkit along with KivyMD.

**Comment by utgupta27** [comment]
@Sumit112192 
How did you get my Github profile ?

**Comment by Sumit112192** [comment]
> @Sumit112192 
> How did you get my Github profile ?

I was searching for issues on GitHub with language python and I got your as one of them.

**Comment by Sumit112192** [comment]
> The layout looks great @Sumit112192. All the best! Hit [me](linkedin.com/in/sanskar10100) or [Utsav](linkedin.com/in/oo7coolutsav) on LinkedIn if you think we can help!

That's not my layout. That is your friend layout. I will definitely follow you but currently I don't have account on LinkedIn.

**Comment by utgupta27** [comment]
> hey @Sumit112192 ,
> I created a new branch, issue a pull request in this new branch - https://github.com/oo7coolutsav/ytdownloader/tree/mp3-fix-pydub , because main branch now has 3 conflicts with this request.
> I fixed this MP3-issue using moviepy library in my main branch.
> 

@Sumit112192 
You have not created a pull request on this branch till now.

**Comment by Sumit112192** [comment]
> > hey @Sumit112192 ,
> > I created a new branch, issue a pull request in this new branch - https://github.com/oo7coolutsav/ytdownloader/tree/mp3-fix-pydub , because main branch now has 3 conflicts with this request.
> > I fixed this MP3-issue using moviepy library in my main branch.
> > 
> 
> @Sumit112192 
> You have not created a pull request on this branch till now.

You said that you did solve the issue with moviepy so I am not creating any pull request now.

**Comment by utgupta27** [comment]
> > > hey @Sumit112192 ,
> > > I created a new branch, issue a pull request in this new branch - https://github.com/oo7coolutsav/ytdownloader/tree/mp3-fix-pydub , because main branch now has 3 conflicts with this request.
> > > I fixed this MP3-issue using moviepy library in my main branch.
> > > 
> > 
> > @Sumit112192 
> > You have not created a pull request on this branch till now.
> 
> You said that you did solve the issue with moviepy so I am not creating any pull request now.

Okay then I am closing this PR.
And thanks for Helping @Sumit112192 .

**Pull request closed without merging**
